# Cloudflare Pages configuration for Next.js with API routes

[build]
command = "npx @cloudflare/next-on-pages@1"
publish = ".vercel/output/static"

[build.environment]
NODE_VERSION = "18"
NEXT_TELEMETRY_DISABLED = "1"

# Functions configuration for Cloudflare Pages
[functions]
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat_populate_process_env"]

[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

[[headers]]
for = "/api/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
