[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"
OAUTH_USER = "your-oauth-user"
OAUTH_CLIENT_ID = "your-oauth-client-id"
OAUTH_CLIENT_SECRET = "your-oauth-client-secret"
OAUTH_REFRESH_TOKEN = "your-oauth-refresh-token"

[env.preview]
NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"
OAUTH_USER = "your-oauth-user"
OAUTH_CLIENT_ID = "your-oauth-client-id"
OAUTH_CLIENT_SECRET = "your-oauth-client-secret"
OAUTH_REFRESH_TOKEN = "your-oauth-refresh-token" 